// Code generated by go-swagger; DO NOT EDIT.

package v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV2Params creates a new GetV2Params object
// with the default values initialized.
func NewGetV2Params() *GetV2Params {

	return &GetV2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV2ParamsWithTimeout creates a new GetV2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV2ParamsWithTimeout(timeout time.Duration) *GetV2Params {

	return &GetV2Params{

		timeout: timeout,
	}
}

// NewGetV2ParamsWithContext creates a new GetV2Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetV2ParamsWithContext(ctx context.Context) *GetV2Params {

	return &GetV2Params{

		Context: ctx,
	}
}

// NewGetV2ParamsWithHTTPClient creates a new GetV2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV2ParamsWithHTTPClient(client *http.Client) *GetV2Params {

	return &GetV2Params{
		HTTPClient: client,
	}
}

/*GetV2Params contains all the parameters to send to the API endpoint
for the get v2 operation typically these are written to a http.Request
*/
type GetV2Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v2 params
func (o *GetV2Params) WithTimeout(timeout time.Duration) *GetV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v2 params
func (o *GetV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v2 params
func (o *GetV2Params) WithContext(ctx context.Context) *GetV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v2 params
func (o *GetV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v2 params
func (o *GetV2Params) WithHTTPClient(client *http.Client) *GetV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v2 params
func (o *GetV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
