// Code generated by go-swagger; DO NOT EDIT.

package layer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV2NameBlobsDigestParams creates a new GetV2NameBlobsDigestParams object
// with the default values initialized.
func NewGetV2NameBlobsDigestParams() *GetV2NameBlobsDigestParams {
	var ()
	return &GetV2NameBlobsDigestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV2NameBlobsDigestParamsWithTimeout creates a new GetV2NameBlobsDigestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV2NameBlobsDigestParamsWithTimeout(timeout time.Duration) *GetV2NameBlobsDigestParams {
	var ()
	return &GetV2NameBlobsDigestParams{

		timeout: timeout,
	}
}

// NewGetV2NameBlobsDigestParamsWithContext creates a new GetV2NameBlobsDigestParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV2NameBlobsDigestParamsWithContext(ctx context.Context) *GetV2NameBlobsDigestParams {
	var ()
	return &GetV2NameBlobsDigestParams{

		Context: ctx,
	}
}

// NewGetV2NameBlobsDigestParamsWithHTTPClient creates a new GetV2NameBlobsDigestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV2NameBlobsDigestParamsWithHTTPClient(client *http.Client) *GetV2NameBlobsDigestParams {
	var ()
	return &GetV2NameBlobsDigestParams{
		HTTPClient: client,
	}
}

/*GetV2NameBlobsDigestParams contains all the parameters to send to the API endpoint
for the get v2 name blobs digest operation typically these are written to a http.Request
*/
type GetV2NameBlobsDigestParams struct {

	/*Digest
	  Digest of a desired BLOB

	*/
	Digest string
	/*Name
	  Name of the image (including the namespace)

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) WithTimeout(timeout time.Duration) *GetV2NameBlobsDigestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) WithContext(ctx context.Context) *GetV2NameBlobsDigestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) WithHTTPClient(client *http.Client) *GetV2NameBlobsDigestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDigest adds the digest to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) WithDigest(digest string) *GetV2NameBlobsDigestParams {
	o.SetDigest(digest)
	return o
}

// SetDigest adds the digest to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) SetDigest(digest string) {
	o.Digest = digest
}

// WithName adds the name to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) WithName(name string) *GetV2NameBlobsDigestParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get v2 name blobs digest params
func (o *GetV2NameBlobsDigestParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetV2NameBlobsDigestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param digest
	if err := r.SetPathParam("digest", o.Digest); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
