// Code generated by go-swagger; DO NOT EDIT.

package layer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutV2NameBlobsUploadsUUIDParams creates a new PutV2NameBlobsUploadsUUIDParams object
// with the default values initialized.
func NewPutV2NameBlobsUploadsUUIDParams() *PutV2NameBlobsUploadsUUIDParams {
	var ()
	return &PutV2NameBlobsUploadsUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutV2NameBlobsUploadsUUIDParamsWithTimeout creates a new PutV2NameBlobsUploadsUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutV2NameBlobsUploadsUUIDParamsWithTimeout(timeout time.Duration) *PutV2NameBlobsUploadsUUIDParams {
	var ()
	return &PutV2NameBlobsUploadsUUIDParams{

		timeout: timeout,
	}
}

// NewPutV2NameBlobsUploadsUUIDParamsWithContext creates a new PutV2NameBlobsUploadsUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutV2NameBlobsUploadsUUIDParamsWithContext(ctx context.Context) *PutV2NameBlobsUploadsUUIDParams {
	var ()
	return &PutV2NameBlobsUploadsUUIDParams{

		Context: ctx,
	}
}

// NewPutV2NameBlobsUploadsUUIDParamsWithHTTPClient creates a new PutV2NameBlobsUploadsUUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutV2NameBlobsUploadsUUIDParamsWithHTTPClient(client *http.Client) *PutV2NameBlobsUploadsUUIDParams {
	var ()
	return &PutV2NameBlobsUploadsUUIDParams{
		HTTPClient: client,
	}
}

/*PutV2NameBlobsUploadsUUIDParams contains all the parameters to send to the API endpoint
for the put v2 name blobs uploads UUID operation typically these are written to a http.Request
*/
type PutV2NameBlobsUploadsUUIDParams struct {

	/*Digest
	  Digest of uploaded blob. If present, the upload will be completed, in a single request, with contents of the request body as the resulting blob.

	*/
	Digest string
	/*Name
	  Name of the image (including the namespace)

	*/
	Name string
	/*UUID
	  A uuid identifying the upload.

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) WithTimeout(timeout time.Duration) *PutV2NameBlobsUploadsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) WithContext(ctx context.Context) *PutV2NameBlobsUploadsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) WithHTTPClient(client *http.Client) *PutV2NameBlobsUploadsUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDigest adds the digest to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) WithDigest(digest string) *PutV2NameBlobsUploadsUUIDParams {
	o.SetDigest(digest)
	return o
}

// SetDigest adds the digest to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) SetDigest(digest string) {
	o.Digest = digest
}

// WithName adds the name to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) WithName(name string) *PutV2NameBlobsUploadsUUIDParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) SetName(name string) {
	o.Name = name
}

// WithUUID adds the uuid to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) WithUUID(uuid string) *PutV2NameBlobsUploadsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the put v2 name blobs uploads UUID params
func (o *PutV2NameBlobsUploadsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PutV2NameBlobsUploadsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param digest
	qrDigest := o.Digest
	qDigest := qrDigest
	if qDigest != "" {
		if err := r.SetQueryParam("digest", qDigest); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
