// Code generated by go-swagger; DO NOT EDIT.

package manifest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV2NameManifestsReferenceParams creates a new GetV2NameManifestsReferenceParams object
// with the default values initialized.
func NewGetV2NameManifestsReferenceParams() *GetV2NameManifestsReferenceParams {
	var ()
	return &GetV2NameManifestsReferenceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV2NameManifestsReferenceParamsWithTimeout creates a new GetV2NameManifestsReferenceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV2NameManifestsReferenceParamsWithTimeout(timeout time.Duration) *GetV2NameManifestsReferenceParams {
	var ()
	return &GetV2NameManifestsReferenceParams{

		timeout: timeout,
	}
}

// NewGetV2NameManifestsReferenceParamsWithContext creates a new GetV2NameManifestsReferenceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV2NameManifestsReferenceParamsWithContext(ctx context.Context) *GetV2NameManifestsReferenceParams {
	var ()
	return &GetV2NameManifestsReferenceParams{

		Context: ctx,
	}
}

// NewGetV2NameManifestsReferenceParamsWithHTTPClient creates a new GetV2NameManifestsReferenceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV2NameManifestsReferenceParamsWithHTTPClient(client *http.Client) *GetV2NameManifestsReferenceParams {
	var ()
	return &GetV2NameManifestsReferenceParams{
		HTTPClient: client,
	}
}

/*GetV2NameManifestsReferenceParams contains all the parameters to send to the API endpoint
for the get v2 name manifests reference operation typically these are written to a http.Request
*/
type GetV2NameManifestsReferenceParams struct {

	/*Name
	  Name of the image (including the namespace)

	*/
	Name string
	/*Reference
	  A tag or a digest, pointing to a specific image

	*/
	Reference string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) WithTimeout(timeout time.Duration) *GetV2NameManifestsReferenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) WithContext(ctx context.Context) *GetV2NameManifestsReferenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) WithHTTPClient(client *http.Client) *GetV2NameManifestsReferenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) WithName(name string) *GetV2NameManifestsReferenceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) SetName(name string) {
	o.Name = name
}

// WithReference adds the reference to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) WithReference(reference string) *GetV2NameManifestsReferenceParams {
	o.SetReference(reference)
	return o
}

// SetReference adds the reference to the get v2 name manifests reference params
func (o *GetV2NameManifestsReferenceParams) SetReference(reference string) {
	o.Reference = reference
}

// WriteToRequest writes these params to a swagger request
func (o *GetV2NameManifestsReferenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param reference
	if err := r.SetPathParam("reference", o.Reference); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
