// Code generated by go-swagger; DO NOT EDIT.

package acr_repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAcrV1NameParams creates a new DeleteAcrV1NameParams object
// with the default values initialized.
func NewDeleteAcrV1NameParams() *DeleteAcrV1NameParams {
	var ()
	return &DeleteAcrV1NameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAcrV1NameParamsWithTimeout creates a new DeleteAcrV1NameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAcrV1NameParamsWithTimeout(timeout time.Duration) *DeleteAcrV1NameParams {
	var ()
	return &DeleteAcrV1NameParams{

		timeout: timeout,
	}
}

// NewDeleteAcrV1NameParamsWithContext creates a new DeleteAcrV1NameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAcrV1NameParamsWithContext(ctx context.Context) *DeleteAcrV1NameParams {
	var ()
	return &DeleteAcrV1NameParams{

		Context: ctx,
	}
}

// NewDeleteAcrV1NameParamsWithHTTPClient creates a new DeleteAcrV1NameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAcrV1NameParamsWithHTTPClient(client *http.Client) *DeleteAcrV1NameParams {
	var ()
	return &DeleteAcrV1NameParams{
		HTTPClient: client,
	}
}

/*DeleteAcrV1NameParams contains all the parameters to send to the API endpoint
for the delete acr v1 name operation typically these are written to a http.Request
*/
type DeleteAcrV1NameParams struct {

	/*Name
	  Name of the image (including the namespace)

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete acr v1 name params
func (o *DeleteAcrV1NameParams) WithTimeout(timeout time.Duration) *DeleteAcrV1NameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete acr v1 name params
func (o *DeleteAcrV1NameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete acr v1 name params
func (o *DeleteAcrV1NameParams) WithContext(ctx context.Context) *DeleteAcrV1NameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete acr v1 name params
func (o *DeleteAcrV1NameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete acr v1 name params
func (o *DeleteAcrV1NameParams) WithHTTPClient(client *http.Client) *DeleteAcrV1NameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete acr v1 name params
func (o *DeleteAcrV1NameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete acr v1 name params
func (o *DeleteAcrV1NameParams) WithName(name string) *DeleteAcrV1NameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete acr v1 name params
func (o *DeleteAcrV1NameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAcrV1NameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
