// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAcrV1NameMetadataMetadataParams creates a new DeleteAcrV1NameMetadataMetadataParams object
// with the default values initialized.
func NewDeleteAcrV1NameMetadataMetadataParams() *DeleteAcrV1NameMetadataMetadataParams {
	var ()
	return &DeleteAcrV1NameMetadataMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAcrV1NameMetadataMetadataParamsWithTimeout creates a new DeleteAcrV1NameMetadataMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAcrV1NameMetadataMetadataParamsWithTimeout(timeout time.Duration) *DeleteAcrV1NameMetadataMetadataParams {
	var ()
	return &DeleteAcrV1NameMetadataMetadataParams{

		timeout: timeout,
	}
}

// NewDeleteAcrV1NameMetadataMetadataParamsWithContext creates a new DeleteAcrV1NameMetadataMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAcrV1NameMetadataMetadataParamsWithContext(ctx context.Context) *DeleteAcrV1NameMetadataMetadataParams {
	var ()
	return &DeleteAcrV1NameMetadataMetadataParams{

		Context: ctx,
	}
}

// NewDeleteAcrV1NameMetadataMetadataParamsWithHTTPClient creates a new DeleteAcrV1NameMetadataMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAcrV1NameMetadataMetadataParamsWithHTTPClient(client *http.Client) *DeleteAcrV1NameMetadataMetadataParams {
	var ()
	return &DeleteAcrV1NameMetadataMetadataParams{
		HTTPClient: client,
	}
}

/*DeleteAcrV1NameMetadataMetadataParams contains all the parameters to send to the API endpoint
for the delete acr v1 name metadata metadata operation typically these are written to a http.Request
*/
type DeleteAcrV1NameMetadataMetadataParams struct {

	/*Metadata
	  Name of the metadata

	*/
	Metadata string
	/*Name
	  Name of the image (including the namespace)

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) WithTimeout(timeout time.Duration) *DeleteAcrV1NameMetadataMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) WithContext(ctx context.Context) *DeleteAcrV1NameMetadataMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) WithHTTPClient(client *http.Client) *DeleteAcrV1NameMetadataMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMetadata adds the metadata to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) WithMetadata(metadata string) *DeleteAcrV1NameMetadataMetadataParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) SetMetadata(metadata string) {
	o.Metadata = metadata
}

// WithName adds the name to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) WithName(name string) *DeleteAcrV1NameMetadataMetadataParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete acr v1 name metadata metadata params
func (o *DeleteAcrV1NameMetadataMetadataParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAcrV1NameMetadataMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param metadata
	if err := r.SetPathParam("metadata", o.Metadata); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
