// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAcrV1NameTagsReferenceParams creates a new DeleteAcrV1NameTagsReferenceParams object
// with the default values initialized.
func NewDeleteAcrV1NameTagsReferenceParams() *DeleteAcrV1NameTagsReferenceParams {
	var ()
	return &DeleteAcrV1NameTagsReferenceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAcrV1NameTagsReferenceParamsWithTimeout creates a new DeleteAcrV1NameTagsReferenceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAcrV1NameTagsReferenceParamsWithTimeout(timeout time.Duration) *DeleteAcrV1NameTagsReferenceParams {
	var ()
	return &DeleteAcrV1NameTagsReferenceParams{

		timeout: timeout,
	}
}

// NewDeleteAcrV1NameTagsReferenceParamsWithContext creates a new DeleteAcrV1NameTagsReferenceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAcrV1NameTagsReferenceParamsWithContext(ctx context.Context) *DeleteAcrV1NameTagsReferenceParams {
	var ()
	return &DeleteAcrV1NameTagsReferenceParams{

		Context: ctx,
	}
}

// NewDeleteAcrV1NameTagsReferenceParamsWithHTTPClient creates a new DeleteAcrV1NameTagsReferenceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAcrV1NameTagsReferenceParamsWithHTTPClient(client *http.Client) *DeleteAcrV1NameTagsReferenceParams {
	var ()
	return &DeleteAcrV1NameTagsReferenceParams{
		HTTPClient: client,
	}
}

/*DeleteAcrV1NameTagsReferenceParams contains all the parameters to send to the API endpoint
for the delete acr v1 name tags reference operation typically these are written to a http.Request
*/
type DeleteAcrV1NameTagsReferenceParams struct {

	/*Name
	  Name of the image (including the namespace)

	*/
	Name string
	/*Reference
	  A tag or a digest, pointing to a specific image

	*/
	Reference string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) WithTimeout(timeout time.Duration) *DeleteAcrV1NameTagsReferenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) WithContext(ctx context.Context) *DeleteAcrV1NameTagsReferenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) WithHTTPClient(client *http.Client) *DeleteAcrV1NameTagsReferenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) WithName(name string) *DeleteAcrV1NameTagsReferenceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) SetName(name string) {
	o.Name = name
}

// WithReference adds the reference to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) WithReference(reference string) *DeleteAcrV1NameTagsReferenceParams {
	o.SetReference(reference)
	return o
}

// SetReference adds the reference to the delete acr v1 name tags reference params
func (o *DeleteAcrV1NameTagsReferenceParams) SetReference(reference string) {
	o.Reference = reference
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAcrV1NameTagsReferenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param reference
	if err := r.SetPathParam("reference", o.Reference); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
