// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAcrV1NameManifestsReferenceMetadataParams creates a new GetAcrV1NameManifestsReferenceMetadataParams object
// with the default values initialized.
func NewGetAcrV1NameManifestsReferenceMetadataParams() *GetAcrV1NameManifestsReferenceMetadataParams {
	var ()
	return &GetAcrV1NameManifestsReferenceMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAcrV1NameManifestsReferenceMetadataParamsWithTimeout creates a new GetAcrV1NameManifestsReferenceMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAcrV1NameManifestsReferenceMetadataParamsWithTimeout(timeout time.Duration) *GetAcrV1NameManifestsReferenceMetadataParams {
	var ()
	return &GetAcrV1NameManifestsReferenceMetadataParams{

		timeout: timeout,
	}
}

// NewGetAcrV1NameManifestsReferenceMetadataParamsWithContext creates a new GetAcrV1NameManifestsReferenceMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAcrV1NameManifestsReferenceMetadataParamsWithContext(ctx context.Context) *GetAcrV1NameManifestsReferenceMetadataParams {
	var ()
	return &GetAcrV1NameManifestsReferenceMetadataParams{

		Context: ctx,
	}
}

// NewGetAcrV1NameManifestsReferenceMetadataParamsWithHTTPClient creates a new GetAcrV1NameManifestsReferenceMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAcrV1NameManifestsReferenceMetadataParamsWithHTTPClient(client *http.Client) *GetAcrV1NameManifestsReferenceMetadataParams {
	var ()
	return &GetAcrV1NameManifestsReferenceMetadataParams{
		HTTPClient: client,
	}
}

/*GetAcrV1NameManifestsReferenceMetadataParams contains all the parameters to send to the API endpoint
for the get acr v1 name manifests reference metadata operation typically these are written to a http.Request
*/
type GetAcrV1NameManifestsReferenceMetadataParams struct {

	/*Name
	  Name of the image (including the namespace)

	*/
	Name string
	/*Reference
	  A tag or a digest, pointing to a specific image

	*/
	Reference string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) WithTimeout(timeout time.Duration) *GetAcrV1NameManifestsReferenceMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) WithContext(ctx context.Context) *GetAcrV1NameManifestsReferenceMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) WithHTTPClient(client *http.Client) *GetAcrV1NameManifestsReferenceMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) WithName(name string) *GetAcrV1NameManifestsReferenceMetadataParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) SetName(name string) {
	o.Name = name
}

// WithReference adds the reference to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) WithReference(reference string) *GetAcrV1NameManifestsReferenceMetadataParams {
	o.SetReference(reference)
	return o
}

// SetReference adds the reference to the get acr v1 name manifests reference metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataParams) SetReference(reference string) {
	o.Reference = reference
}

// WriteToRequest writes these params to a swagger request
func (o *GetAcrV1NameManifestsReferenceMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param reference
	if err := r.SetPathParam("reference", o.Reference); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
