// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAcrV1NameManifestsReferenceMetadataMetadataParams creates a new GetAcrV1NameManifestsReferenceMetadataMetadataParams object
// with the default values initialized.
func NewGetAcrV1NameManifestsReferenceMetadataMetadataParams() *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	var ()
	return &GetAcrV1NameManifestsReferenceMetadataMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAcrV1NameManifestsReferenceMetadataMetadataParamsWithTimeout creates a new GetAcrV1NameManifestsReferenceMetadataMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAcrV1NameManifestsReferenceMetadataMetadataParamsWithTimeout(timeout time.Duration) *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	var ()
	return &GetAcrV1NameManifestsReferenceMetadataMetadataParams{

		timeout: timeout,
	}
}

// NewGetAcrV1NameManifestsReferenceMetadataMetadataParamsWithContext creates a new GetAcrV1NameManifestsReferenceMetadataMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAcrV1NameManifestsReferenceMetadataMetadataParamsWithContext(ctx context.Context) *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	var ()
	return &GetAcrV1NameManifestsReferenceMetadataMetadataParams{

		Context: ctx,
	}
}

// NewGetAcrV1NameManifestsReferenceMetadataMetadataParamsWithHTTPClient creates a new GetAcrV1NameManifestsReferenceMetadataMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAcrV1NameManifestsReferenceMetadataMetadataParamsWithHTTPClient(client *http.Client) *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	var ()
	return &GetAcrV1NameManifestsReferenceMetadataMetadataParams{
		HTTPClient: client,
	}
}

/*GetAcrV1NameManifestsReferenceMetadataMetadataParams contains all the parameters to send to the API endpoint
for the get acr v1 name manifests reference metadata metadata operation typically these are written to a http.Request
*/
type GetAcrV1NameManifestsReferenceMetadataMetadataParams struct {

	/*Metadata
	  Name of the metadata

	*/
	Metadata string
	/*Name
	  Name of the image (including the namespace)

	*/
	Name string
	/*Reference
	  A tag or a digest, pointing to a specific image

	*/
	Reference string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) WithTimeout(timeout time.Duration) *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) WithContext(ctx context.Context) *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) WithHTTPClient(client *http.Client) *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMetadata adds the metadata to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) WithMetadata(metadata string) *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) SetMetadata(metadata string) {
	o.Metadata = metadata
}

// WithName adds the name to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) WithName(name string) *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) SetName(name string) {
	o.Name = name
}

// WithReference adds the reference to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) WithReference(reference string) *GetAcrV1NameManifestsReferenceMetadataMetadataParams {
	o.SetReference(reference)
	return o
}

// SetReference adds the reference to the get acr v1 name manifests reference metadata metadata params
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) SetReference(reference string) {
	o.Reference = reference
}

// WriteToRequest writes these params to a swagger request
func (o *GetAcrV1NameManifestsReferenceMetadataMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param metadata
	if err := r.SetPathParam("metadata", o.Metadata); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param reference
	if err := r.SetPathParam("reference", o.Reference); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
