// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAcrV1NameMetadataParams creates a new GetAcrV1NameMetadataParams object
// with the default values initialized.
func NewGetAcrV1NameMetadataParams() *GetAcrV1NameMetadataParams {
	var ()
	return &GetAcrV1NameMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAcrV1NameMetadataParamsWithTimeout creates a new GetAcrV1NameMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAcrV1NameMetadataParamsWithTimeout(timeout time.Duration) *GetAcrV1NameMetadataParams {
	var ()
	return &GetAcrV1NameMetadataParams{

		timeout: timeout,
	}
}

// NewGetAcrV1NameMetadataParamsWithContext creates a new GetAcrV1NameMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAcrV1NameMetadataParamsWithContext(ctx context.Context) *GetAcrV1NameMetadataParams {
	var ()
	return &GetAcrV1NameMetadataParams{

		Context: ctx,
	}
}

// NewGetAcrV1NameMetadataParamsWithHTTPClient creates a new GetAcrV1NameMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAcrV1NameMetadataParamsWithHTTPClient(client *http.Client) *GetAcrV1NameMetadataParams {
	var ()
	return &GetAcrV1NameMetadataParams{
		HTTPClient: client,
	}
}

/*GetAcrV1NameMetadataParams contains all the parameters to send to the API endpoint
for the get acr v1 name metadata operation typically these are written to a http.Request
*/
type GetAcrV1NameMetadataParams struct {

	/*Name
	  Name of the image (including the namespace)

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get acr v1 name metadata params
func (o *GetAcrV1NameMetadataParams) WithTimeout(timeout time.Duration) *GetAcrV1NameMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get acr v1 name metadata params
func (o *GetAcrV1NameMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get acr v1 name metadata params
func (o *GetAcrV1NameMetadataParams) WithContext(ctx context.Context) *GetAcrV1NameMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get acr v1 name metadata params
func (o *GetAcrV1NameMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get acr v1 name metadata params
func (o *GetAcrV1NameMetadataParams) WithHTTPClient(client *http.Client) *GetAcrV1NameMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get acr v1 name metadata params
func (o *GetAcrV1NameMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get acr v1 name metadata params
func (o *GetAcrV1NameMetadataParams) WithName(name string) *GetAcrV1NameMetadataParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get acr v1 name metadata params
func (o *GetAcrV1NameMetadataParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAcrV1NameMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
