// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAcrV1NameTagsParams creates a new GetAcrV1NameTagsParams object
// with the default values initialized.
func NewGetAcrV1NameTagsParams() *GetAcrV1NameTagsParams {
	var ()
	return &GetAcrV1NameTagsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAcrV1NameTagsParamsWithTimeout creates a new GetAcrV1NameTagsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAcrV1NameTagsParamsWithTimeout(timeout time.Duration) *GetAcrV1NameTagsParams {
	var ()
	return &GetAcrV1NameTagsParams{

		timeout: timeout,
	}
}

// NewGetAcrV1NameTagsParamsWithContext creates a new GetAcrV1NameTagsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAcrV1NameTagsParamsWithContext(ctx context.Context) *GetAcrV1NameTagsParams {
	var ()
	return &GetAcrV1NameTagsParams{

		Context: ctx,
	}
}

// NewGetAcrV1NameTagsParamsWithHTTPClient creates a new GetAcrV1NameTagsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAcrV1NameTagsParamsWithHTTPClient(client *http.Client) *GetAcrV1NameTagsParams {
	var ()
	return &GetAcrV1NameTagsParams{
		HTTPClient: client,
	}
}

/*GetAcrV1NameTagsParams contains all the parameters to send to the API endpoint
for the get acr v1 name tags operation typically these are written to a http.Request
*/
type GetAcrV1NameTagsParams struct {

	/*Last
	  query parameter for the last item in previou query

	*/
	Last *string
	/*N
	  query parameter for max number of items

	*/
	N *string
	/*Name
	  Name of the image (including the namespace)

	*/
	Name string
	/*Orderby
	  orderby query parameter

	*/
	Orderby *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) WithTimeout(timeout time.Duration) *GetAcrV1NameTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) WithContext(ctx context.Context) *GetAcrV1NameTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) WithHTTPClient(client *http.Client) *GetAcrV1NameTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLast adds the last to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) WithLast(last *string) *GetAcrV1NameTagsParams {
	o.SetLast(last)
	return o
}

// SetLast adds the last to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) SetLast(last *string) {
	o.Last = last
}

// WithN adds the n to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) WithN(n *string) *GetAcrV1NameTagsParams {
	o.SetN(n)
	return o
}

// SetN adds the n to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) SetN(n *string) {
	o.N = n
}

// WithName adds the name to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) WithName(name string) *GetAcrV1NameTagsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) SetName(name string) {
	o.Name = name
}

// WithOrderby adds the orderby to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) WithOrderby(orderby *string) *GetAcrV1NameTagsParams {
	o.SetOrderby(orderby)
	return o
}

// SetOrderby adds the orderby to the get acr v1 name tags params
func (o *GetAcrV1NameTagsParams) SetOrderby(orderby *string) {
	o.Orderby = orderby
}

// WriteToRequest writes these params to a swagger request
func (o *GetAcrV1NameTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Last != nil {

		// query param last
		var qrLast string
		if o.Last != nil {
			qrLast = *o.Last
		}
		qLast := qrLast
		if qLast != "" {
			if err := r.SetQueryParam("last", qLast); err != nil {
				return err
			}
		}

	}

	if o.N != nil {

		// query param n
		var qrN string
		if o.N != nil {
			qrN = *o.N
		}
		qN := qrN
		if qN != "" {
			if err := r.SetQueryParam("n", qN); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Orderby != nil {

		// query param orderby
		var qrOrderby string
		if o.Orderby != nil {
			qrOrderby = *o.Orderby
		}
		qOrderby := qrOrderby
		if qOrderby != "" {
			if err := r.SetQueryParam("orderby", qOrderby); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
