// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAcrV1NameParams creates a new GetAcrV1NameParams object
// with the default values initialized.
func NewGetAcrV1NameParams() *GetAcrV1NameParams {
	var ()
	return &GetAcrV1NameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAcrV1NameParamsWithTimeout creates a new GetAcrV1NameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAcrV1NameParamsWithTimeout(timeout time.Duration) *GetAcrV1NameParams {
	var ()
	return &GetAcrV1NameParams{

		timeout: timeout,
	}
}

// NewGetAcrV1NameParamsWithContext creates a new GetAcrV1NameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAcrV1NameParamsWithContext(ctx context.Context) *GetAcrV1NameParams {
	var ()
	return &GetAcrV1NameParams{

		Context: ctx,
	}
}

// NewGetAcrV1NameParamsWithHTTPClient creates a new GetAcrV1NameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAcrV1NameParamsWithHTTPClient(client *http.Client) *GetAcrV1NameParams {
	var ()
	return &GetAcrV1NameParams{
		HTTPClient: client,
	}
}

/*GetAcrV1NameParams contains all the parameters to send to the API endpoint
for the get acr v1 name operation typically these are written to a http.Request
*/
type GetAcrV1NameParams struct {

	/*Name
	  Name of the image (including the namespace)

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get acr v1 name params
func (o *GetAcrV1NameParams) WithTimeout(timeout time.Duration) *GetAcrV1NameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get acr v1 name params
func (o *GetAcrV1NameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get acr v1 name params
func (o *GetAcrV1NameParams) WithContext(ctx context.Context) *GetAcrV1NameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get acr v1 name params
func (o *GetAcrV1NameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get acr v1 name params
func (o *GetAcrV1NameParams) WithHTTPClient(client *http.Client) *GetAcrV1NameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get acr v1 name params
func (o *GetAcrV1NameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get acr v1 name params
func (o *GetAcrV1NameParams) WithName(name string) *GetAcrV1NameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get acr v1 name params
func (o *GetAcrV1NameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAcrV1NameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
