// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPatchAcrV1NameParams creates a new PatchAcrV1NameParams object
// with the default values initialized.
func NewPatchAcrV1NameParams() *PatchAcrV1NameParams {
	var ()
	return &PatchAcrV1NameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAcrV1NameParamsWithTimeout creates a new PatchAcrV1NameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchAcrV1NameParamsWithTimeout(timeout time.Duration) *PatchAcrV1NameParams {
	var ()
	return &PatchAcrV1NameParams{

		timeout: timeout,
	}
}

// NewPatchAcrV1NameParamsWithContext creates a new PatchAcrV1NameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchAcrV1NameParamsWithContext(ctx context.Context) *PatchAcrV1NameParams {
	var ()
	return &PatchAcrV1NameParams{

		Context: ctx,
	}
}

// NewPatchAcrV1NameParamsWithHTTPClient creates a new PatchAcrV1NameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchAcrV1NameParamsWithHTTPClient(client *http.Client) *PatchAcrV1NameParams {
	var ()
	return &PatchAcrV1NameParams{
		HTTPClient: client,
	}
}

/*PatchAcrV1NameParams contains all the parameters to send to the API endpoint
for the patch acr v1 name operation typically these are written to a http.Request
*/
type PatchAcrV1NameParams struct {

	/*Name
	  Name of the image (including the namespace)

	*/
	Name string
	/*Value*/
	Value string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch acr v1 name params
func (o *PatchAcrV1NameParams) WithTimeout(timeout time.Duration) *PatchAcrV1NameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch acr v1 name params
func (o *PatchAcrV1NameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch acr v1 name params
func (o *PatchAcrV1NameParams) WithContext(ctx context.Context) *PatchAcrV1NameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch acr v1 name params
func (o *PatchAcrV1NameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch acr v1 name params
func (o *PatchAcrV1NameParams) WithHTTPClient(client *http.Client) *PatchAcrV1NameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch acr v1 name params
func (o *PatchAcrV1NameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the patch acr v1 name params
func (o *PatchAcrV1NameParams) WithName(name string) *PatchAcrV1NameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the patch acr v1 name params
func (o *PatchAcrV1NameParams) SetName(name string) {
	o.Name = name
}

// WithValue adds the value to the patch acr v1 name params
func (o *PatchAcrV1NameParams) WithValue(value string) *PatchAcrV1NameParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the patch acr v1 name params
func (o *PatchAcrV1NameParams) SetValue(value string) {
	o.Value = value
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAcrV1NameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Value); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
