// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAcrV1NameTagsReferenceMetadataMetadataParams creates a new PutAcrV1NameTagsReferenceMetadataMetadataParams object
// with the default values initialized.
func NewPutAcrV1NameTagsReferenceMetadataMetadataParams() *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	var ()
	return &PutAcrV1NameTagsReferenceMetadataMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAcrV1NameTagsReferenceMetadataMetadataParamsWithTimeout creates a new PutAcrV1NameTagsReferenceMetadataMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAcrV1NameTagsReferenceMetadataMetadataParamsWithTimeout(timeout time.Duration) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	var ()
	return &PutAcrV1NameTagsReferenceMetadataMetadataParams{

		timeout: timeout,
	}
}

// NewPutAcrV1NameTagsReferenceMetadataMetadataParamsWithContext creates a new PutAcrV1NameTagsReferenceMetadataMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAcrV1NameTagsReferenceMetadataMetadataParamsWithContext(ctx context.Context) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	var ()
	return &PutAcrV1NameTagsReferenceMetadataMetadataParams{

		Context: ctx,
	}
}

// NewPutAcrV1NameTagsReferenceMetadataMetadataParamsWithHTTPClient creates a new PutAcrV1NameTagsReferenceMetadataMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAcrV1NameTagsReferenceMetadataMetadataParamsWithHTTPClient(client *http.Client) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	var ()
	return &PutAcrV1NameTagsReferenceMetadataMetadataParams{
		HTTPClient: client,
	}
}

/*PutAcrV1NameTagsReferenceMetadataMetadataParams contains all the parameters to send to the API endpoint
for the put acr v1 name tags reference metadata metadata operation typically these are written to a http.Request
*/
type PutAcrV1NameTagsReferenceMetadataMetadataParams struct {

	/*Metadata
	  Name of the metadata

	*/
	Metadata string
	/*Name
	  Name of the image (including the namespace)

	*/
	Name string
	/*Reference
	  A tag or a digest, pointing to a specific image

	*/
	Reference string
	/*Value*/
	Value string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) WithTimeout(timeout time.Duration) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) WithContext(ctx context.Context) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) WithHTTPClient(client *http.Client) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMetadata adds the metadata to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) WithMetadata(metadata string) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) SetMetadata(metadata string) {
	o.Metadata = metadata
}

// WithName adds the name to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) WithName(name string) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) SetName(name string) {
	o.Name = name
}

// WithReference adds the reference to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) WithReference(reference string) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	o.SetReference(reference)
	return o
}

// SetReference adds the reference to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) SetReference(reference string) {
	o.Reference = reference
}

// WithValue adds the value to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) WithValue(value string) *PutAcrV1NameTagsReferenceMetadataMetadataParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the put acr v1 name tags reference metadata metadata params
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) SetValue(value string) {
	o.Value = value
}

// WriteToRequest writes these params to a swagger request
func (o *PutAcrV1NameTagsReferenceMetadataMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param metadata
	if err := r.SetPathParam("metadata", o.Metadata); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param reference
	if err := r.SetPathParam("reference", o.Reference); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Value); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
