// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAcrV1NameMetadataMetadataParams creates a new PutAcrV1NameMetadataMetadataParams object
// with the default values initialized.
func NewPutAcrV1NameMetadataMetadataParams() *PutAcrV1NameMetadataMetadataParams {
	var ()
	return &PutAcrV1NameMetadataMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAcrV1NameMetadataMetadataParamsWithTimeout creates a new PutAcrV1NameMetadataMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAcrV1NameMetadataMetadataParamsWithTimeout(timeout time.Duration) *PutAcrV1NameMetadataMetadataParams {
	var ()
	return &PutAcrV1NameMetadataMetadataParams{

		timeout: timeout,
	}
}

// NewPutAcrV1NameMetadataMetadataParamsWithContext creates a new PutAcrV1NameMetadataMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAcrV1NameMetadataMetadataParamsWithContext(ctx context.Context) *PutAcrV1NameMetadataMetadataParams {
	var ()
	return &PutAcrV1NameMetadataMetadataParams{

		Context: ctx,
	}
}

// NewPutAcrV1NameMetadataMetadataParamsWithHTTPClient creates a new PutAcrV1NameMetadataMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAcrV1NameMetadataMetadataParamsWithHTTPClient(client *http.Client) *PutAcrV1NameMetadataMetadataParams {
	var ()
	return &PutAcrV1NameMetadataMetadataParams{
		HTTPClient: client,
	}
}

/*PutAcrV1NameMetadataMetadataParams contains all the parameters to send to the API endpoint
for the put acr v1 name metadata metadata operation typically these are written to a http.Request
*/
type PutAcrV1NameMetadataMetadataParams struct {

	/*Metadata
	  Name of the metadata

	*/
	Metadata string
	/*Name
	  Name of the image (including the namespace)

	*/
	Name string
	/*Value*/
	Value string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) WithTimeout(timeout time.Duration) *PutAcrV1NameMetadataMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) WithContext(ctx context.Context) *PutAcrV1NameMetadataMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) WithHTTPClient(client *http.Client) *PutAcrV1NameMetadataMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMetadata adds the metadata to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) WithMetadata(metadata string) *PutAcrV1NameMetadataMetadataParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) SetMetadata(metadata string) {
	o.Metadata = metadata
}

// WithName adds the name to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) WithName(name string) *PutAcrV1NameMetadataMetadataParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) SetName(name string) {
	o.Name = name
}

// WithValue adds the value to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) WithValue(value string) *PutAcrV1NameMetadataMetadataParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the put acr v1 name metadata metadata params
func (o *PutAcrV1NameMetadataMetadataParams) SetValue(value string) {
	o.Value = value
}

// WriteToRequest writes these params to a swagger request
func (o *PutAcrV1NameMetadataMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param metadata
	if err := r.SetPathParam("metadata", o.Metadata); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Value); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
