// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Layers layers
// swagger:model Layers
type Layers struct {

	// fs layers
	FsLayers []*LayersFsLayersItems0 `json:"fsLayers"`

	// history
	History string `json:"history,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// signature
	Signature string `json:"signature,omitempty"`

	// tag
	Tag string `json:"tag,omitempty"`
}

// Validate validates this layers
func (m *Layers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFsLayers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Layers) validateFsLayers(formats strfmt.Registry) error {

	if swag.IsZero(m.FsLayers) { // not required
		return nil
	}

	for i := 0; i < len(m.FsLayers); i++ {
		if swag.IsZero(m.FsLayers[i]) { // not required
			continue
		}

		if m.FsLayers[i] != nil {
			if err := m.FsLayers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("fsLayers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Layers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Layers) UnmarshalBinary(b []byte) error {
	var res Layers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LayersFsLayersItems0 layers fs layers items0
// swagger:model LayersFsLayersItems0
type LayersFsLayersItems0 struct {

	// blob sum
	BlobSum string `json:"blobSum,omitempty"`
}

// Validate validates this layers fs layers items0
func (m *LayersFsLayersItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LayersFsLayersItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LayersFsLayersItems0) UnmarshalBinary(b []byte) error {
	var res LayersFsLayersItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
