// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TagAttributeList tag attribute list
// swagger:model TagAttributeList
type TagAttributeList struct {

	// image name
	ImageName string `json:"imageName,omitempty"`

	// registry
	Registry string `json:"registry,omitempty"`

	// tags
	Tags []*TagAttributeListTagsItems0 `json:"tags"`
}

// Validate validates this tag attribute list
func (m *TagAttributeList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TagAttributeList) validateTags(formats strfmt.Registry) error {

	if swag.IsZero(m.Tags) { // not required
		return nil
	}

	for i := 0; i < len(m.Tags); i++ {
		if swag.IsZero(m.Tags[i]) { // not required
			continue
		}

		if m.Tags[i] != nil {
			if err := m.Tags[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tags" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TagAttributeList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TagAttributeList) UnmarshalBinary(b []byte) error {
	var res TagAttributeList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TagAttributeListTagsItems0 tag attribute list tags items0
// swagger:model TagAttributeListTagsItems0
type TagAttributeListTagsItems0 struct {

	// changeable attributes
	ChangeableAttributes *TagAttributeListTagsItems0ChangeableAttributes `json:"changeableAttributes,omitempty"`

	// created time
	CreatedTime string `json:"createdTime,omitempty"`

	// digest
	Digest string `json:"digest,omitempty"`

	// last update time
	LastUpdateTime string `json:"lastUpdateTime,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// quarantine state
	QuarantineState string `json:"quarantineState,omitempty"`

	// signature record
	SignatureRecord string `json:"signatureRecord,omitempty"`
}

// Validate validates this tag attribute list tags items0
func (m *TagAttributeListTagsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChangeableAttributes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TagAttributeListTagsItems0) validateChangeableAttributes(formats strfmt.Registry) error {

	if swag.IsZero(m.ChangeableAttributes) { // not required
		return nil
	}

	if m.ChangeableAttributes != nil {
		if err := m.ChangeableAttributes.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("changeableAttributes")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TagAttributeListTagsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TagAttributeListTagsItems0) UnmarshalBinary(b []byte) error {
	var res TagAttributeListTagsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TagAttributeListTagsItems0ChangeableAttributes tag attribute list tags items0 changeable attributes
// swagger:model TagAttributeListTagsItems0ChangeableAttributes
type TagAttributeListTagsItems0ChangeableAttributes struct {

	// delete enabled
	DeleteEnabled bool `json:"deleteEnabled,omitempty"`

	// list enabled
	ListEnabled bool `json:"listEnabled,omitempty"`

	// read enabled
	ReadEnabled bool `json:"readEnabled,omitempty"`

	// write enabled
	WriteEnabled bool `json:"writeEnabled,omitempty"`
}

// Validate validates this tag attribute list tags items0 changeable attributes
func (m *TagAttributeListTagsItems0ChangeableAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TagAttributeListTagsItems0ChangeableAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TagAttributeListTagsItems0ChangeableAttributes) UnmarshalBinary(b []byte) error {
	var res TagAttributeListTagsItems0ChangeableAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
